# This generates a long-lived client certificate useful for testing

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-cert
  namespace: default
spec:
  isCA: false
  secretName: client-cert
  subject:
    organizations:
    - cert-manager
  uris:
  - spiffe://tim-ramlot-gcp.jetstacker.net/client-cert
  duration: 8760h  # 1 year
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: workload-issuer
    kind: ClusterIssuer
    group: cert-manager.io
