apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: default
spec:
  containers:
  - name: client-workload
    image: cert-manager.local/client-workload:latest
    imagePullPolicy: Never

    env:
    - {name: "AWS_ENABLE", value: "true"}
    - {name: "AWS_AUDIENCE", value: "aws"}
    - {name: "AWS_ROLE", value: "<ROLE>"}

    - {name: "AZURE_ENABLE", value: "true"}
    - {name: "AZURE_AUDIENCE", value: "azure"}
    - {name: "AZURE_APPLICATION_ID", value: "<APPLICATION_ID>"}
    - {name: "AZURE_TENANT_ID", value: "<TENANT_ID>"}

    - {name: "GCLOUD_ENABLE", value: "true"}
    - {name: "GCLOUD_AUDIENCE", value: "gcloud"}
    - {name: "GCLOUD_SA", value: "<SA_NAME>@<PROJECT_NAME>.iam.gserviceaccount.com"}
    - {name: "GCLOUD_PROVIDER", value: "//iam.googleapis.com/projects/<PROJECT_ID>/locations/global/workloadIdentityPools/<POOL_NAME>/providers/<PROVIDER_NAME>"}
    - {name: "GCLOUD_PROJECT", value: "<PROJECT_NAME>"}

    command: ['sh', '-c', 'workload.init.sh && sleep 3600']

    volumeMounts:
    - mountPath: "/var/run/secrets/spiffe.io"
      name: spiffe
  volumes:
    - name: spiffe
      csi:
        driver: csi.cert-manager.io
        readOnly: true
        volumeAttributes:
          csi.cert-manager.io/issuer-name: workload-issuer
          csi.cert-manager.io/issuer-kind: ClusterIssuer
          csi.cert-manager.io/issuer-group: cert-manager.io

          csi.cert-manager.io/uri-sans: spiffe://tim-ramlot-gcp.jetstacker.net/workload
