apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: default
spec:
  containers:
  - name: client-workload
    image: cert-manager.local/client-workload:latest
    imagePullPolicy: Never

    env:
    - {name: "AWS_ENABLE", value: "true"}
    - {name: "AWS_AUDIENCE", value: "aws"}
    - {name: "AWS_ROLE", value: "arn:aws:iam::334114465092:role/KubeCon_NA_24_DEMO"}

    - {name: "AZURE_ENABLE", value: "true"}
    - {name: "AZURE_AUDIENCE", value: "azure"}
    - {name: "AZURE_APPLICATION_ID", value: "20166ed5-aa01-447e-8f7c-6c169f7a9487"}
    - {name: "AZURE_TENANT_ID", value: "0192a697-ddb9-4a76-8a03-89b135007265"}

    - {name: "GCLOUD_ENABLE", value: "true"}
    - {name: "GCLOUD_AUDIENCE", value: "gcloud"}
    - {name: "GCLOUD_SA", value: "kubecon-na-24-demo@jetstack-tim-ramlot.iam.gserviceaccount.com"}
    - {name: "GCLOUD_PROVIDER", value: "//iam.googleapis.com/projects/17852703695/locations/global/workloadIdentityPools/kubecon-na-24-demo/providers/demo"}
    - {name: "GCLOUD_PROJECT", value: "jetstack-tim-ramlot"}

    command: ['sh', '-c', 'workload.init.sh && sleep 3600']

    volumeMounts:
    - mountPath: "/var/run/secrets/spiffe.io"
      name: spiffe
  volumes:
    - name: spiffe
      csi:
        driver: csi.cert-manager.io
        readOnly: true
        volumeAttributes:
          csi.cert-manager.io/issuer-name: workload-issuer
          csi.cert-manager.io/issuer-kind: ClusterIssuer
          csi.cert-manager.io/issuer-group: cert-manager.io

          csi.cert-manager.io/uri-sans: spiffe://tim-ramlot-gcp.jetstacker.net/workload
