apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: default
spec:
  containers:
  - name: client-workload
    image: cert-manager.local/client-workload:latest
    imagePullPolicy: Never
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']

    volumeMounts:
    - mountPath: "/var/run/secrets/spiffe.io"
      name: spiffe
  volumes:
    - name: spiffe
      csi:
        driver: csi.cert-manager.io
        readOnly: true
        volumeAttributes:
          csi.cert-manager.io/issuer-name: workload-issuer
          csi.cert-manager.io/issuer-kind: ClusterIssuer
          csi.cert-manager.io/issuer-group: cert-manager.io

          csi.cert-manager.io/uri-sans: spiffe://tim-ramlot-gcp.jetstacker.net/workload
